spring:
  datasource:
    driver-class-name: com.mongodb.Mongo
  data:
    mongodb:
      host: localhost
      database: api
      port: 27017
logging:
  level:
    ROOT: DEBUG
  debug: true

resource:
  caminhoAnexo: "d:\\listaFuncionarios.txt"
